### ISSUE TITLE
update examples 

### ISSUE THREAD

**Issue by JM-FRANCE** [bricofoy/yasm#11]
in your blink examples you use the built in LED and usually have a line such as
`#define LedPin 		13  //pin 13 because most arduino boards provide a led here`

This is un-necessary as most Arduino boards have a pin connected to an on-board LED in series with a resistor and the IDE constant **LED_BUILTIN** is the number of the pin to which the on-board LED is connected (Most boards have this LED connected to digital pin 13).

Would suggest you use LED_BUILTIN instead of 13 (or remove your #define and use LED_BUILTIN directly in the code but that's less flexible)

**Comment by bricofoy** [comment]
sure, thanks for the hint. I'll change it. Or you may want to submit pull request ?
