### ISSUE TITLE
bool isInState(void (*state)())

### ISSUE THREAD

**Issue by tenm90** [bricofoy/yasm#14]
Sorry, I am quite a novice, but are using YASM and very enthousiastic about it. But there is one thing that I don's get right. It is while using 'bool isInState(void (*state)())'.
There is no example for this method in the repository.
Say my machine is called myMachine and one of the states in that machine is called myState. How would I use the method (written out, please) to check that I am in that state?

Thank you so much! Have a very nice day, Theo

**Comment by bricofoy** [comment]
Hi
Well, is pretty straightforward to use, just do something like :
`
if (myMachine.isInState(myState)) { .... }`

You can call it either from the main loop or from inside another machine. You may also call it from inside the machine, it will work with no error, but it's useless.
I added this method because I needed it for a project, and I had no time to add example for it... Thanks for reminding me this :)

**Comment by bricofoy** [comment]
you can see a real use case here :
[https://github.com/bricofoy/dominicis/blob/master/menu.ino#L66](https://github.com/bricofoy/dominicis/blob/master/menu.ino#L66)

**Comment by tenm90** [comment]
You are very welcome! I am a big fan of your FSM support library. Thanks
for your explanation and all the best from Holland!

Hans

Op ma 5 okt. 2020 om 18:04 schreef bricofoy <notifications@github.com>:

**Comment by bricofoy** [comment]
Great, you are only the second person that I know who is using my library :)

If you can give a link to your project using it, I would love to have a look at it.
best regards from France
Yann

**Comment by tenm90** [comment]
Hello Yann,

Sorry it took me so long to answer, but some things in life can take your
mind completely off programming for a long time. Hope you are very well,
despite this pandemic that is so much affecting our lives (at least, my
life).
I'm a bloody amature to programming. Started for fun with Basic years ago
and since my retirement in C++ for Arduino. I enclose my source so far.
It's a combination of old school linear programming with a touch of object
oriented. And YASM of course! So you will be laughing your head off! Please
don't bother trying to professionalise my source, this is about as far as
it gets from my point of knowledge and understanding, and so far I'm pretty
satisfied with my results. It won't compile at this moment because I'm
still experimenting with things I like to alter. Programming keeps my brain
busy now that I am retired. But you helped me so nicely and said you would
love to look at my work, so here it is!
I'm struggling now with something I want to do with the method that was the
subject of my question in the first place:

 (myMachine.isInState(myState)) { .... }

I want to use it in a loop where <myState> comes from a lookup table (const
char table[x]), but the compiler keeps complaining about non matching
arguments. Maybe you could shed some light on this?

Thank you so much, greetings from a sunny Holland, Hans

Op ma 2 nov. 2020 om 20:03 schreef bricofoy ***@***.***>:
