### ISSUE TITLE
option to set isFirstRun to true on resume

### ISSUE THREAD

**Issue by ClaesClaes** [bricofoy/yasm#15]
Hi,
I'm using your lib to implement a menu displayed on an OLED. Works great and makes the task very easy. I'm now wondering if it's possible to change the `resume()` function so that it could optionally resume the state with setting the `isFirstRun` to true? Something like `StateMachine.resume(true)`.

My menu is only refreshed when user change a rotary encoder.
However the application also stop the StateMachine periodically, to do other tasks (displaying other parameters on the OLED) and then resume the last state.
When the program returns to the state it was stopped in it skips refreshing the OLED because I use the `isFirstRun` flag to refresh the OLED. I could refresh every time the state is run through but it would be unnecessary workload and a waste of processor cycles. I could also check which `state` was stopped and do `next(state, true)` but it can be in any of some 15 states and it would be tedious to check for all with a switch statement.
Any tip or hint on how I could do this would be extremely helpful.

**Comment by bricofoy** [comment]
done.

please update your library using arduino library manager, you should get 1.1.0 and be able to use StateMachine.resume(true); to reset running info while restarting the machine, just like with next()

**Comment by bricofoy** [comment]
If possible, I would love to see your code using the library. Do you have it on github ?

It's only the second time I ear about someone using my lib :)

**Comment by ClaesClaes** [comment]
That was quick and much appreciated. Tested, and it works perfectly. Thanks a lot! I'm quite new to this (covid-lockdown hobby) so I have not used GitHub for my project. The state machine menu its part of a bigger code project but I could share the flowchart so you see how I've used your lib.

**Comment by bricofoy** [comment]
Yes, please, I'm curious. I created it for my own use, and I'm curious about what can be done with it :)

you can send me directly files on bricofoy<at>free.fr

thanks

**Comment by ClaesClaes** [comment]
Sure, I made an overview state diagram and a short video so the diagram makes more sense. I'll send it to the email address you have listed in your source code.
